### ISSUE TITLE
DataExplorer should also provide a view to the Workspace

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#187] opened 2019-12-29 11:13 UTC
Currently the DataExplorer shows:

- Drives
- Home
- User-Location

but we also have a concept of "Workspace" where projects are located in. These can currently only be accessed via the 'ProjectExplorer'. We should therefore provide a new tab named 'projects' that list all workspace projects/locations and allows to open files from there.

When this is done, we should decide what functionality of project-explorer is still required and maybe integrate this in the Data-Explorer view so we can on the long term get rid of the ProjectExplorer.

**Comment by laeubi** [comment] 2019-12-29 11:20
The following features of ProjectExplorer are currently missing in DataExplorer but could be useful anyways:

- copy/paste/delete/move operations
- creating new items via wizard in selected location
- ... ?

**Comment by Mailaender** [comment] 2021-06-25 05:35
Reverse duplicate of https://github.com/eclipse/chemclipse/issues/437.

**Closed as completed** 2022-06-09 15:40 UTC
