### ISSUE TITLE
Process Method Settings are not Persistent

### ISSUE THREAD

**Issue by kerner1000** [eclipse-chemclipse/chemclipse#220] opened 2020-01-17 15:06 UTC
settings shown here are not persistent.

![method-settings](https://user-images.githubusercontent.com/13817521/72622325-43b8d480-3943-11ea-9999-09fd67c5e34f.png)

**Comment by laeubi** [comment] 2020-04-04 10:23
Duplicate of #271

**Closed as completed by laeubi** 2020-04-04 10:23 UTC
Labels: duplicate
